name: kubez-dev
services:
  keycloak:
    image: 'quay.io/keycloak/keycloak:26.2.4'
    container_name: keycloak
    restart: always
    hostname: '0.0.0.0'
    privileged: true
    environment:
        KC_BOOTSTRAP_ADMIN_USERNAME: 'admin'
        KC_BOOTSTRAP_ADMIN_PASSWORD: 'admin'
    ports:
        - '8090:8080'
    command: start-dev
    volumes:
      - ./data/keycloak:/opt/keycloak/data/

  openfga:
    image: openfga/openfga:latest
    container_name: openfga
    restart: always
    ports:
        - '8080:8080'
        - '8081:8081'
        - '3000:3000'
    command: run